import { useEffect, useState } from 'react'
import { BrainCircuit, CheckCircle2, FileSearch, Loader2, Sparkles, TrendingUp, Lightbulb, ShieldCheck } from 'lucide-react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { dataApi } from '@/lib/api'
import { Button } from '@/components/ui/button'

export function AnalysisWorkspace() {
  const [selected, setSelected] = useState<string[]>([])
  const [mergeFiles, setMergeFiles] = useState(true)
  const [message, setMessage] = useState('')
  const [model, setModel] = useState('deepseek-chat')
  const [modelMessage, setModelMessage] = useState('')
  const [selectedThemes, setSelectedThemes] = useState<string[]>([])
  const [customThemes, setCustomThemes] = useState('')
  const [resultPath, setResultPath] = useState('')
  const [batchSummaries, setBatchSummaries] = useState<{ batch: number; record_count: number; summary?: string; topics?: string[] }[]>([])
  const [batchResults, setBatchResults] = useState<{ path: string; status: 'completed' | 'failed'; error?: string; input_count?: number; output_count?: number }[]>([])
  const [intelligence, setIntelligence] = useState<{ topics: { topic: string; content_count: number; platforms: Record<string, number>; representative_terms: string[]; recent_count: number; trend: string; evidence_count: number; quality_score: number }[]; research_directions: { research_direction: string; score: number; topic: string; why_now: string; research_questions: string[]; recommended_methods: string[]; evidence_topics: string[] }[] }>()
  const { data } = useQuery({ queryKey: ['analysisFiles'], queryFn: async () => (await dataApi.getFiles(undefined, undefined, false)).data.files, staleTime: 5000 })
  const { data: aiConfig } = useQuery({ queryKey: ['analysisConfig'], queryFn: async () => (await dataApi.getAnalysisConfig()).data, retry: 1 })
  const models = aiConfig?.models?.length ? aiConfig.models : [{ value: 'deepseek-chat', label: 'DeepSeek Chat' }, { value: 'deepseek-reasoner', label: 'DeepSeek Reasoner' }]
  useEffect(() => { if (aiConfig?.model) setModel(aiConfig.model) }, [aiConfig?.model])
  const files = (data || []).filter((file) => ['jsonl', 'json', 'csv', 'xlsx', 'xls'].includes(file.type.toLowerCase()) && !file.path.split(/[\\/]/).includes('scientist'))
  const fileGroups = [
    { label: '内容文件', hint: '文章、论文与公开内容，适合研究主题分析', files: files.filter((file) => /(?:^|_)contents(?:_|\.)/i.test(file.name)) },
    { label: '评论文件', hint: '评论与讨论内容，适合观点和风险信号分析', files: files.filter((file) => /(?:^|_)comments?(?:_|\.)/i.test(file.name)) },
    { label: '其他采集文件', hint: '未按内容或评论命名的原始采集文件', files: files.filter((file) => !/(?:^|_)(?:contents|comments?)(?:_|\.)/i.test(file.name)) },
  ].filter((group) => group.files.length > 0)
  const resultQuery = useQuery({ queryKey: ['analysisResult', resultPath], queryFn: async () => (await dataApi.getFileContent(resultPath, 30)).data, enabled: Boolean(resultPath) })
  const toggleTheme = (theme: string) => setSelectedThemes((current) => current.includes(theme) ? current.filter((item) => item !== theme) : [...current, theme])
  const parsedCustomThemes = customThemes.split(/[，,\n]/).map((item) => item.trim()).filter(Boolean)
  const hasScope = selectedThemes.length > 0 || parsedCustomThemes.length > 0
  const toggleFile = (path: string) => setSelected((current) => current.includes(path) ? current.filter((item) => item !== path) : [...current, path])
  const mutation = useMutation({ mutationFn: () => dataApi.analyzeMany(selected, selectedThemes, parsedCustomThemes, 500, mergeFiles), onSuccess: (response) => { const completed = response.data.results.filter((item) => item.status === 'completed' && item.result); const first = completed[0]?.result; if (first) { setResultPath(first.output_file); setBatchSummaries(first.batch_summaries || []); setIntelligence(first.intelligence) } setBatchResults(response.data.results.map((item) => ({ path: item.path, status: item.status, error: item.error, input_count: item.result?.input_count, output_count: item.result?.output_count }))); setMessage(`${mergeFiles ? '合并分析' : '批量分析'}完成：${response.data.completed} 个成功，${response.data.failed} 个失败。${first ? `当前展示第一个成功文件的结果。` : ''}`) }, onError: (error: Error) => setMessage(`分析失败：${error.message}`) })

  return <div className="max-w-4xl mx-auto space-y-6">
    <div><div className="flex items-center gap-3"><BrainCircuit className="w-6 h-6 text-cyan-300" /><h1 className="text-xl font-semibold">内容分析</h1></div></div>
    <section className="rounded-xl border border-white/[0.08] bg-[#202020] p-5">
      <div className="mb-5"><div className="flex items-center justify-between"><div><h2 className="font-medium">AI 批次总结模型</h2><p className="text-xs text-zinc-500 mt-1">选择用于批次总结和研究情报归纳的模型。</p></div><span className="text-xs text-zinc-500">{aiConfig?.ai_enabled ? 'API 已配置' : '未配置 API Key'}</span></div><div className="mt-3 grid grid-cols-2 md:grid-cols-3 gap-2">{models.map((item) => <button type="button" key={item.value} onClick={async () => { setModel(item.value); try { await dataApi.setAnalysisModel(item.value); setModelMessage('模型已保存') } catch { setModelMessage('模型保存失败') } }} className={`text-left rounded-lg border p-3 transition-colors ${model === item.value ? 'border-cyan-400 bg-cyan-400/10' : 'border-white/10 bg-[#171717] hover:border-cyan-400/50'}`}><div className="text-sm font-medium">{item.label}</div></button>)}</div>{modelMessage && <p className="mt-2 text-xs text-emerald-300">{modelMessage}</p>}</div>
      <div className="flex items-start gap-3 mb-5"><FileSearch className="w-5 h-5 text-violet-300 mt-0.5" /><div><h2 className="font-medium">选择采集文件</h2><p className="text-xs text-zinc-500 mt-1">按内容、评论和其他原始采集文件分类；已排除分析结果与生成的 Idea。</p></div></div>
      <div className="rounded-lg border border-white/[0.08] bg-[#171717] overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-white/[0.08] px-3 py-2"><span className="text-xs text-zinc-400">已选 {selected.length} / {files.length} 个文件</span><div className="flex gap-3"><button type="button" onClick={() => setSelected(files.map((file) => file.path))} className="text-xs text-cyan-300 hover:text-cyan-200">全选</button><button type="button" onClick={() => setSelected([])} className="text-xs text-zinc-400 hover:text-zinc-200">清空</button></div></div><div className="max-h-64 overflow-auto">{fileGroups.map((group) => <div key={group.label} className="border-b border-white/[0.06] last:border-b-0"><div className="bg-white/[0.03] px-3 py-2"><p className="text-xs font-medium text-zinc-300">{group.label}<span className="ml-2 font-normal text-zinc-500">{group.files.length} 个</span></p><p className="mt-0.5 text-[11px] text-zinc-500">{group.hint}</p></div>{group.files.map((file) => <label key={file.path} className="flex cursor-pointer items-center gap-3 px-3 py-2.5 hover:bg-white/[0.03]"><input type="checkbox" checked={selected.includes(file.path)} onChange={() => toggleFile(file.path)} className="h-4 w-4 accent-cyan-400" /><span className="min-w-0 flex-1 truncate text-sm text-zinc-200">{file.path}</span><span className="shrink-0 text-xs text-zinc-500">{file.record_count ?? '-'} 条</span></label>)}</div>)}{files.length === 0 && <p className="px-3 py-6 text-center text-sm text-zinc-500">暂无可分析的原始采集文件。</p>}</div></div>
      <div className="mt-5 border-t border-white/[0.08] pt-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-medium">分析范围</h2><p className="mt-1 text-xs text-zinc-500">默认不选。单选会获得更聚焦的趋势与 Idea 证据链；多选适合比较交叉风险。范围外内容不会进入热点、候选方向、知识库同步或后续研究想法。</p></div><button type="button" onClick={() => setSelectedThemes(aiConfig?.themes || [])} className="shrink-0 text-xs text-cyan-300 hover:text-cyan-200">全选固定主题</button></div><div className="mt-3 flex flex-wrap gap-2">{(aiConfig?.themes || []).map((theme) => <button key={theme} type="button" onClick={() => toggleTheme(theme)} className={`rounded-md border px-2.5 py-1.5 text-xs transition-colors ${selectedThemes.includes(theme) ? 'border-cyan-400/70 bg-cyan-400/10 text-cyan-200' : 'border-white/10 bg-[#171717] text-zinc-400 hover:border-cyan-400/50 hover:text-zinc-200'}`}>{theme}</button>)}</div><label className="mt-4 block text-xs text-zinc-400">自定义主题<input value={customThemes} onChange={(event) => setCustomThemes(event.target.value)} placeholder="例如：医疗 AI 安全，多模态模型越狱（用逗号分隔）" className="mt-2 h-10 w-full rounded-md border border-white/10 bg-[#171717] px-3 text-sm text-zinc-100 outline-none focus:border-cyan-400/70" /></label></div>
      <div className="mt-5 flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs text-zinc-300"><input type="checkbox" checked={mergeFiles} onChange={(event) => setMergeFiles(event.target.checked)} className="h-4 w-4 accent-cyan-400" />合并为一个结果文件<span className="text-zinc-500">（同一主题的多文件建议开启）</span></label><Button onClick={() => mutation.mutate()} disabled={selected.length === 0 || !hasScope || mutation.isPending} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300">{mutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}{mutation.isPending ? '正在分析' : mergeFiles ? `合并分析 ${selected.length} 个文件` : `分别分析 ${selected.length} 个文件`}</Button>{!hasScope && <p className="text-xs text-amber-300">请至少选择一个主题或填写自定义主题</p>}{message && <p className="text-sm text-zinc-400 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />{message}</p>}</div>
    </section>
    {batchResults.length > 0 && <section className="rounded-xl border border-white/[0.08] bg-[#202020] p-5"><h2 className="font-medium">批量任务结果</h2><div className="mt-3 space-y-2">{batchResults.map((item) => <div key={item.path} className="flex items-center justify-between gap-3 rounded border border-white/[0.07] bg-[#171717] px-3 py-2 text-xs"><span className="truncate text-zinc-300">{item.path}</span><span className={item.status === 'completed' ? 'shrink-0 text-emerald-300' : 'shrink-0 text-rose-300'}>{item.status === 'completed' ? `完成 · ${item.input_count}→${item.output_count} 条` : `失败 · ${item.error || '未知错误'}`}</span></div>)}</div></section>}
    {resultPath && <section className="rounded-xl border border-cyan-400/20 bg-[#202020] p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-medium">本次分析结果</h2><p className="mt-1 text-xs text-zinc-500">已展示前 30 条，可在采集结果中查看完整文件。</p></div><a href={dataApi.getDownloadUrl(resultPath)} className="text-xs text-cyan-300 hover:text-cyan-200">下载完整结果</a></div>{resultQuery.isLoading ? <p className="text-sm text-zinc-500">正在加载结果…</p> : <div className="space-y-3 max-h-[520px] overflow-auto">{(resultQuery.data?.data || []).map((item, index) => <article key={index} className="rounded-lg border border-white/[0.07] bg-[#171717] p-4"><div className="flex items-start justify-between gap-4"><h3 className="text-sm font-medium text-zinc-100">{String(item.title || `记录 ${index + 1}`)}</h3><span className="text-[11px] text-cyan-300 shrink-0">{item.analysis_method === 'ai' ? 'AI' : '规则'}</span></div>{Boolean(item.summary) && <p className="mt-2 text-sm leading-6 text-zinc-300">{String(item.summary)}</p>}<div className="mt-3 flex flex-wrap gap-2">{(Array.isArray(item.topics) ? item.topics : []).slice(0, 6).map((topic) => <span key={String(topic)} className="rounded-full bg-cyan-400/10 px-2 py-1 text-[11px] text-cyan-200">{String(topic)}</span>)}</div>{Array.isArray(item.evidence) && item.evidence.length > 0 && <div className="mt-3 border-t border-white/[0.06] pt-3"><p className="text-[11px] text-amber-200">证据句</p>{item.evidence.slice(0, 2).map((evidence) => <p key={String(evidence)} className="mt-1 text-xs leading-5 text-zinc-400">“{String(evidence)}”</p>)}</div>}</article>)}</div>}</section>}
    {intelligence && <section className="space-y-4"><div className="flex items-center gap-2"><TrendingUp className="w-5 h-5 text-emerald-300" /><div><h2 className="font-medium">研究风向与候选方向</h2><p className="mt-1 text-xs text-zinc-500">基于内容证据、主题聚合和跨平台覆盖生成，可追溯到下方原始记录。</p></div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{intelligence.research_directions.slice(0, 6).map((direction) => <article key={direction.research_direction} className="rounded-xl border border-emerald-400/20 bg-[#202020] p-4"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><Lightbulb className="w-4 h-4 text-amber-300" /><h3 className="text-sm font-medium">{direction.research_direction}</h3></div><span className="text-xs font-semibold text-emerald-300">{direction.score}/100</span></div><p className="mt-3 text-xs leading-5 text-zinc-300">{direction.why_now}</p><div className="mt-3 space-y-1">{direction.research_questions.map((question) => <p key={question} className="text-xs text-zinc-400">研究问题：{question}</p>)}</div><div className="mt-3 flex flex-wrap gap-1.5">{direction.recommended_methods.map((method) => <span key={method} className="rounded-full bg-emerald-400/10 px-2 py-1 text-[11px] text-emerald-200">{method}</span>)}</div></article>)}</div><div className="grid grid-cols-1 md:grid-cols-3 gap-3">{intelligence.topics.slice(0, 6).map((topic) => <article key={topic.topic} className="rounded-lg border border-white/[0.07] bg-[#1d1d1d] p-4"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-cyan-300" /><h3 className="text-sm font-medium">{topic.topic}</h3></div><span className={`text-[11px] ${topic.trend === 'rising' ? 'text-emerald-300' : 'text-zinc-400'}`}>{topic.trend === 'rising' ? '升温' : '稳定'}</span></div><p className="mt-2 text-xs text-zinc-500">{topic.content_count} 条内容 · {Object.keys(topic.platforms).length} 个平台 · 证据 {topic.evidence_count} 条</p><div className="mt-2 flex flex-wrap gap-1.5">{topic.representative_terms.slice(0, 4).map((term) => <span key={term} className="text-[10px] text-cyan-200">#{term}</span>)}</div></article>)}</div></section>}
    {batchSummaries.length > 0 && <section className="rounded-xl border border-violet-400/20 bg-[#202020] p-5"><div className="mb-4"><h2 className="font-medium">分批 AI 总结</h2><p className="mt-1 text-xs text-zinc-500">每个批次覆盖一段连续记录，便于观察内容或评论观点的变化。</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{batchSummaries.map((batch) => <article key={batch.batch} className="rounded-lg border border-white/[0.07] bg-[#171717] p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-medium">第 {batch.batch} 批</h3><span className="text-[11px] text-violet-300">{batch.record_count} 条</span></div>{batch.summary && <p className="mt-2 text-sm leading-6 text-zinc-300">{batch.summary}</p>}<div className="mt-3 flex flex-wrap gap-2">{(batch.topics || []).map((topic) => <span key={topic} className="rounded-full bg-violet-400/10 px-2 py-1 text-[11px] text-violet-200">{topic}</span>)}</div></article>)}</div></section>}
    <section className="grid grid-cols-1 md:grid-cols-3 gap-3">{[['清洗去重','移除空内容、规范字段、合并重复记录'],['结构化分析','摘要、关键词、主题和来源信息'],['AI 增强（可选）','配置 AI_API_KEY 后补充观点和质量评分']].map(([title, desc]) => <div key={title} className="rounded-lg border border-white/[0.07] bg-[#1d1d1d] p-4"><h3 className="text-sm font-medium">{title}</h3><p className="mt-2 text-xs leading-5 text-zinc-500">{desc}</p></div>)}</section>
  </div>
}
